import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
    "./lib/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        background: "#f8f9fb",
        "on-background": "#191c1e",
        surface: "#f8f9fb",
        "surface-dim": "#d9dadc",
        "surface-bright": "#f8f9fb",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#f2f4f6",
        "surface-container": "#edeef0",
        "surface-container-high": "#e7e8ea",
        "surface-container-highest": "#e1e2e4",
        "surface-variant": "#e1e2e4",
        "on-surface": "#191c1e",
        "on-surface-variant": "#424754",
        "inverse-surface": "#2e3132",
        "inverse-on-surface": "#f0f1f3",
        outline: "#727785",
        "outline-variant": "#c2c6d6",
        "surface-tint": "#005ac2",
        primary: "#0058be",
        "on-primary": "#ffffff",
        "primary-container": "#2170e4",
        "on-primary-container": "#fefcff",
        "inverse-primary": "#adc6ff",
        secondary: "#585e6c",
        "on-secondary": "#ffffff",
        "secondary-container": "#dde2f3",
        "on-secondary-container": "#5e6473",
        tertiary: "#924700",
        "on-tertiary": "#ffffff",
        "tertiary-container": "#b75b00",
        "on-tertiary-container": "#fffbff",
        error: "#ba1a1a",
        "on-error": "#ffffff",
        "error-container": "#ffdad6",
        "on-error-container": "#93000a",
        "primary-fixed": "#d8e2ff",
        "primary-fixed-dim": "#adc6ff",
        "on-primary-fixed": "#001a42",
        "on-primary-fixed-variant": "#004395",
        "secondary-fixed": "#dde2f3",
        "secondary-fixed-dim": "#c1c6d7",
        "on-secondary-fixed": "#161c27",
        "on-secondary-fixed-variant": "#414754",
        "tertiary-fixed": "#ffdcc6",
        "tertiary-fixed-dim": "#ffb786",
        "on-tertiary-fixed": "#311400",
        "on-tertiary-fixed-variant": "#723600",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        sm: "0.125rem",
        md: "0.375rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        unit: "4px",
        gutter: "16px",
        "container-padding": "24px",
        "nav-height": "64px",
        "stack-sm": "8px",
        "stack-md": "16px",
        "stack-lg": "32px",
      },
      fontFamily: {
        sans: ["Inter", "sans-serif"],
        headline: ["Geist", "sans-serif"],
        mono: ["Geist Mono", "monospace"],
        "headline-lg": ["Geist", "sans-serif"],
        "headline-md": ["Geist", "sans-serif"],
        "body-base": ["Inter", "sans-serif"],
        "body-sm": ["Inter", "sans-serif"],
        "mono-base": ["Geist Mono", "monospace"],
        "mono-sm": ["Geist Mono", "monospace"],
        "label-caps": ["Geist", "sans-serif"],
      },
      fontSize: {
        "headline-lg": ["24px", { lineHeight: "32px", letterSpacing: "-0.02em", fontWeight: "600" }],
        "headline-md": ["18px", { lineHeight: "24px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "body-base": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "body-sm": ["12px", { lineHeight: "18px", fontWeight: "400" }],
        "mono-base": ["13px", { lineHeight: "20px", fontWeight: "400" }],
        "mono-sm": ["11px", { lineHeight: "16px", letterSpacing: "0.02em", fontWeight: "500" }],
        "label-caps": ["11px", { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "700" }],
      },
    },
  },
  plugins: [],
};
export default config;

